name: Test Notebooks

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string

jobs:
  find-notebooks:
    runs-on: ubuntu-latest
    outputs:
      notebooks: ${{ steps.notebooks.outputs.notebooks }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Find all notebooks
      id: notebooks
      run: |
        notebooks=$(find notebooks/ -type f -name "*.ipynb" | jq -R -s -c 'split("\n")[:-1]')
        echo "notebooks=$notebooks" >> $GITHUB_OUTPUT

  test-notebook:
    needs: find-notebooks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook: ${{ fromJson(needs.find-notebooks.outputs.notebooks) }}
      fail-fast: false
    outputs:
      resource-failure: ${{ steps.execute.outputs.resource-failure }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        notebook_dir=$(dirname "${{ matrix.notebook }}")
        if [ -f "$notebook_dir/requirements.txt" ]; then
          pip install -r "$notebook_dir/requirements.txt"
        fi

    - name: Execute notebook with resource monitoring
      id: execute
      run: |
        # Function to monitor resources and return status
        execute_with_monitoring() {
          jupyter nbconvert --to notebook --execute "${{ matrix.notebook }}" --output executed_notebook.ipynb &
          JUPYTER_PID=$!
          
          while kill -0 $JUPYTER_PID 2>/dev/null; do
            memory_usage=$(free -m | awk '/Mem:/ {print $3/$2 * 100.0}')
            disk_usage=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
            echo "Memory: ${memory_usage}% | Disk: ${disk_usage}%"
            
            if (( $(echo "$memory_usage > 90" | bc -l) )) || [ "$disk_usage" -gt 90 ]; then
              echo "Resource usage exceeded 90%"
              kill -TERM $JUPYTER_PID
              wait $JUPYTER_PID
              echo "resource-failure=true" >> $GITHUB_OUTPUT
              return 1
            fi
            sleep 5
          done
          
          # Wait for natural completion
          wait $JUPYTER_PID
          return $?
        }

        # Execute with trap for cleanup
        trap 'kill -TERM $JUPYTER_PID 2>/dev/null' EXIT
        if ! execute_with_monitoring; then
          exit 1
        fi

  retry-16gb:
    needs: test-notebook
    if: needs.test-notebook.outputs.resource-failure == 'true'
    runs-on: jwst-pipeline-notebooks-16gb
    strategy:
      matrix:
        notebook: ${{ fromJson(needs.find-notebooks.outputs.notebooks) }}
      fail-fast: false
    outputs:
      resource-failure: ${{ steps.execute.outputs.resource-failure }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        notebook_dir=$(dirname "${{ matrix.notebook }}")
        if [ -f "$notebook_dir/requirements.txt" ]; then
          pip install -r "$notebook_dir/requirements.txt"
        fi

    - name: Execute notebook with resource monitoring
      id: execute
      run: |
        execute_with_monitoring() {
          jupyter nbconvert --to notebook --execute "${{ matrix.notebook }}" --output executed_notebook.ipynb &
          JUPYTER_PID=$!
          
          while kill -0 $JUPYTER_PID 2>/dev/null; do
            memory_usage=$(free -m | awk '/Mem:/ {print $3/$2 * 100.0}')
            disk_usage=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
            echo "Memory: ${memory_usage}% | Disk: ${disk_usage}%"
            
            if (( $(echo "$memory_usage > 90" | bc -l) )) || [ "$disk_usage" -gt 90 ]; then
              echo "Resource usage exceeded 90%"
              kill -TERM $JUPYTER_PID
              wait $JUPYTER_PID
              echo "resource-failure=true" >> $GITHUB_OUTPUT
              return 1
            fi
            sleep 5
          done
          
          wait $JUPYTER_PID
          return $?
        }

        trap 'kill -TERM $JUPYTER_PID 2>/dev/null' EXIT
        if ! execute_with_monitoring; then
          exit 1
        fi

  retry-32gb:
    needs: retry-16gb
    if: needs.retry-16gb.outputs.resource-failure == 'true'
    runs-on: jwst-pipeline-notebooks-32gb
    strategy:
      matrix:
        notebook: ${{ fromJson(needs.find-notebooks.outputs.notebooks) }}
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        notebook_dir=$(dirname "${{ matrix.notebook }}")
        if [ -f "$notebook_dir/requirements.txt" ]; then
          pip install -r "$notebook_dir/requirements.txt"
        fi

    - name: Execute notebook with resource monitoring
      id: execute
      run: |
        execute_with_monitoring() {
          jupyter nbconvert --to notebook --execute "${{ matrix.notebook }}" --output executed_notebook.ipynb &
          JUPYTER_PID=$!
          
          while kill -0 $JUPYTER_PID 2>/dev/null; do
            memory_usage=$(free -m | awk '/Mem:/ {print $3/$2 * 100.0}')
            disk_usage=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
            echo "Memory: ${memory_usage}% | Disk: ${disk_usage}%"
            
            if (( $(echo "$memory_usage > 90" | bc -l) )) || [ "$disk_usage" -gt 90 ]; then
              echo "Resource usage exceeded 90% on all runners"
              kill -TERM $JUPYTER_PID
              wait $JUPYTER_PID
              return 1
            fi
            sleep 5
          done
          
          wait $JUPYTER_PID
          return $?
        }

        trap 'kill -TERM $JUPYTER_PID 2>/dev/null' EXIT
        if ! execute_with_monitoring; then
          echo "Notebook failed on all runners"
          exit 1
        fi
