name: HTML Book Builder Trigger

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-html:
    if: github.event.pull_request.merged == true
    uses: mgough-970/dev-actions/.github/workflows/ci_html_builder.yml@v1
    with:
      python-version: 3.11
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
