name: CI Unified Runner

on:
  workflow_dispatch:
    inputs:
      execution-mode:
        description: "Mode of execution: all notebooks, changed only, or a single notebook"
        type: choice
        options: [all, changed, single]
        default: all

      single-filename:
        description: "Notebook filename for single mode (example: JWPipeNB-MIRI-MRS.ipynb)"
        type: string
        required: false

      build-html:
        description: "Whether to trigger HTML book rebuild after execution"
        type: boolean
        default: true

      security-scan:
        description: "Run Bandit security scan on notebook scripts"
        type: boolean
        default: true

      use-conda:
        description: "Use conda environment (instead of just pip)"
        type: boolean
        default: false

      conda-environment-file:
        description: "Path to environment.yml file (if any)"
        type: string
        required: false

      conda-packages:
        description: "Comma-separated packages to install from conda-forge (if needed)"
        type: string
        required: false

  pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**/*.ipynb'
      - 'static/**'
      - '*.md'

  schedule:
    - cron: '0 5 * * *'

jobs:
  run-ci:
    uses: mgough-970/dev-actions/.github/workflows/ci_pipeline.yml@v1
    with:
      python-version: 3.11
      execution-mode: ${{ inputs.execution-mode }}
      single-filename: ${{ inputs.single-filename }}
      build-html: ${{ inputs.build-html }}
      security-scan: ${{ inputs.security-scan }}
      use-conda: ${{ inputs.use-conda }}
      conda-environment-file: ${{ inputs.conda-environment-file }}
      conda-packages: ${{ inputs.conda-packages }}
    secrets:
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
