name: Deprecate Notebook

on:
  workflow_dispatch:
    inputs:
      notebook_name:
        description: 'The name of the notebook to deprecate (e.g., example.ipynb)'
        required: true
        default: 'example.ipynb'

jobs:
  deprecate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set notebook path
        id: path
        run: |
          NOTEBOOK_NAME="${{ github.event.inputs.notebook_name }}"
          if [ -f "$NOTEBOOK_NAME" ]; then
            echo "notebook_path=${NOTEBOOK_NAME}" >> $GITHUB_ENV
          else
            echo "::error::Notebook '${NOTEBOOK_NAME}' not found."
            exit 1
          fi

      - name: Check for deprecated tag
        id: check_deprecated
        run: |
          notebook_path="${{ env.notebook_path }}"
          if jq '.metadata.deprecated == true' "$notebook_path"; then
            echo "::error::Notebook '${{ env.notebook_path }}' is already flagged as deprecated."
            exit 0
          fi

      - name: Add deprecated tag
        run: |
          notebook_path="${{ env.notebook_path }}"
          jq '.metadata.deprecated = true' "$notebook_path" > temp.ipynb && mv temp.ipynb "$notebook_path"

      - name: Add deprecation banner
        run: |
          notebook_path="${{ env.notebook_path }}"
          BANNER_CELL=$(jq -n \
            --arg text "**⚠️ This notebook is scheduled for deprecation. Please use with caution.**" \
            '{"cell_type": "markdown", "metadata": {"deprecation": true}, "source": [$text]}')
          jq ".cells |= [$BANNER_CELL] + ." "$notebook_path" > temp.ipynb && mv temp.ipynb "$notebook_path"

      - name: Commit and push to gh-storage branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -B gh-storage
          git add "${{ env.notebook_path }}"
          git commit -m "Deprecate notebook ${{ env.notebook_path }}"
          git push origin gh-storage --force
