name: List Changed Files

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to check for changed files'
        required: true
        default: 'notebook-ci-testing'
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'spacetelescope/${{ github.event.inputs.repository }}'
          ref: 'gh-pages'
          fetch-depth: 0 # Fetches all history (safest for tracking across multiple push commits)

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47.0.6

      - name: List added or modified files
        run: |
          echo "Added files: ${{ steps.changed-files.outputs.added_files }}"
          echo "Modified files: ${{ steps.changed-files.outputs.modified_files }}"
          # combine added and modified files into a single list
          CHANGED_FILES="${{ steps.changed-files.outputs.added_files }} ${{ steps.changed-files.outputs.modified_files }}"
          echo "All new or changed files: $CHANGED_FILES"
          # filter for .html files
          HTML_FILES=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep '\.html$' || true)
          echo "New or changed HTML files: $HTML_FILES"
