name: GitHub Accessibility Scanner testing
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(s) to scan'
        required: false
        default: 'https://spacetelescope.github.io/notebook-ci-testing/notebooks/**/*.html'

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        id: generate_cache_key
        run: |
          CACHE_KEY=$(printf 'cached_results-%s.json' "${{ github.ref_name }}" | tr -cs 'A-Za-z0-9._-' '-')
          echo "cache_key=$CACHE_KEY" >> $GITHUB_OUTPUT
      - uses: github/accessibility-scanner@v3.2.0
        with:
          urls: |
            ${{ github.event.inputs.url }}
          repository: spacetelescope/notebook-ci-testing
          token: ${{ secrets.A11Y_TOKEN }} # This token must have write access to the repo above (contents, issues, and PRs); more information below. Note: GitHub Actions' GITHUB_TOKEN cannot be used here.
          cache_key: ${{ steps.generate_cache_key.outputs.cache_key }}
