# Merge/Push workflow for hellouniverse repository
# Copy this file to your repository's .github/workflows/ directory

name: Notebook CI - Merge

on:
  push:
    branches: [ main ]
    paths:
      - 'notebooks/**'
      - 'requirements.txt'

jobs:
  notebook-ci:
    uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook-ci-unified.yml@dev-actions-v2
    with:
      # Repository-specific configuration
      notebook_path: 'notebooks'
      python_version: '3.11'
      
      # Merge-specific execution settings
      execution_mode: 'force_execute'
      notebook_pattern: ''
      
      # Environment settings
      environment_file: 'requirements.txt'
      conda_environment_file: ''
      
      # Security and validation
      security_check: true
      notebook_validation: true
      
      # Documentation generation
      generate_docs: true
      docs_artifact: 'hellouniverse-docs'
      
      # Artifact settings
      artifact_retention_days: 30
      
      # Performance settings
      timeout_minutes: 45
      max_parallel: 3
      
    secrets: inherit
