# Example workflow for running notebook CI on pull requests
# Copy this file to your repository's .github/workflows/ directory

name: Notebook CI - Pull Request

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'notebooks/**'
      - '*.yml'
      - '*.yaml'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  validate-notebooks:
    uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_pipeline.yml@main
    with:
      python-version: "3.11"
      execution-mode: "validation-only"
      build-html: false
      security-scan: true
    secrets:
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}

  build-docs-preview:
    uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_html_builder.yml@main
    with:
      python-version: "3.11"
      post-run-script: "scripts/jdaviz_image_replacement.sh"  # Optional
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
