name: Build HTML on merge

on:
  pull_request_target:
    types: [closed]
    paths:
      - '**.ipynb'
      - '**.md'
      - '**.html'

env:
  CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
  CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}

jobs:
  prepare_matrix:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      notebooks: ${{ steps.set-matrix.outputs.notebooks }}
      assets: ${{ steps.set-matrix.outputs.assets }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - id: set-matrix
        shell: bash
        run: |
          # Gather changed files between base and head of the merged PR
          mapfile -t CHANGED <<< "$(git diff --name-only \
            ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }})"

          # Split into notebooks and static assets
          NOTEBOOKS=()
          ASSETS=()
          for f in "${CHANGED[@]}"; do
            case "$f" in
              *.ipynb)
                NOTEBOOKS+=("$f")
                ;;
              *.md|*.MD|*.html|*.htm)
                ASSETS+=("$f")
                ;;
            esac
          done

          nb_json=$(printf '%s\n' "${NOTEBOOKS[@]}" | jq -R -s -c 'split("\n")[:-1]')
          assets_json=$(printf '%s\n' "${ASSETS[@]}"     | jq -R -s -c 'split("\n")[:-1]')

          echo "notebooks=$nb_json" >> "$GITHUB_OUTPUT"
          echo "assets=$assets_json" >> "$GITHUB_OUTPUT"

  execute-notebooks:
    if: github.event.pull_request.merged == true && needs.prepare_matrix.outputs.notebooks != '[]'
    needs: prepare_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebooks: ${{ fromJson(needs.prepare_matrix.outputs.notebooks) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up micromamba and install dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: hstcal
          create-args: >-
            -c conda-forge
            python=${{ vars.PYTHON_VERSION }}
            setuptools=65.5.1
            numpy=1.26.0
            hstcal
            jupyter
            pytest
            nbval
            nbconvert
            bandit

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@v6.0.1
        with:
          version: "0.7.3"
          python-version: ${{ vars.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        env:
          PYDEVD_DISABLE_FILE_VALIDATION: 1
          SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True
        shell: bash
        run: |
          eval "$(micromamba shell hook -s posix)"
          micromamba activate hstcal

          python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"

          echo "Path to req's: $(dirname "${{ matrix.notebooks }}")/requirements.txt"
          ls "$(dirname "${{ matrix.notebooks }}")" || true
          echo ---

          if [ -f "$(dirname "${{ matrix.notebooks }}")/pre-install.sh" ]; then
            chmod +x "$(dirname "${{ matrix.notebooks }}")/pre-install.sh"
            "./$(dirname "${{ matrix.notebooks }}")/pre-install.sh"
          fi
          if [ -f "$(dirname "${{ matrix.notebooks }}")/pre-requirements.sh" ]; then
            chmod +x "$(dirname "${{ matrix.notebooks }}")/pre-requirements.sh"
            "./$(dirname "${{ matrix.notebooks }}")/pre-requirements.sh"
          fi
          if [ -f "$(dirname "${{ matrix.notebooks }}")/pre-requirements.txt" ]; then
            uv pip install --system --no-build-isolation -r "$(dirname "${{ matrix.notebooks }}")/pre-requirements.txt"
          fi
          if [ -f "$(dirname "${{ matrix.notebooks }}")/requirements.txt" ]; then
            uv pip install --system --no-build-isolation -r "$(dirname "${{ matrix.notebooks }}")/requirements.txt"
          fi

          uv pip install --system pytest nbval nbconvert bandit

      - name: Execute notebooks
        id: execute
        shell: bash
        run: |
          eval "$(micromamba shell hook -s posix)"
          micromamba activate hstcal
          if ! jupyter nbconvert --to notebook --execute --inplace "${{ matrix.notebooks }}"; then
            python .github/scripts/insert_failure_message.py "${{ matrix.notebooks }}"
          fi

      - name: Commit modified notebook on current branch
        shell: bash
        run: |
          git config user.name 'CI Bot'
          git config user.email 'action@github.com'
          git add "${{ matrix.notebooks }}"
          git commit -m "Storing executed notebook ${{ matrix.notebooks }}" || echo "No changes to commit."

      - name: Checkout only the file to the gh-storage branch
        shell: bash
        run: |
          git fetch origin gh-storage:gh-storage || git checkout -b gh-storage
          git checkout gh-storage
          git checkout @{-1} -- "${{ matrix.notebooks }}"

      - name: Commit and push notebook to gh-storage
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'CI Bot'
          git config user.email 'action@github.com'
          git add "${{ matrix.notebooks }}"
          git commit -m "Storing executed notebook ${{ matrix.notebooks }}" || echo "No changes to commit."
          MAX_RETRIES=5
          for i in $(seq 1 $MAX_RETRIES); do
            git push origin gh-storage --force && break || {
              echo "Push $i failed... retrying"
              sleep 10
            }
          done

  sync-static:
    if: github.event.pull_request.merged == true && needs.prepare_matrix.outputs.assets != '[]'
    needs: prepare_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        asset: ${{ fromJson(needs.prepare_matrix.outputs.assets) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Copy static file to gh-storage
        shell: bash
        env:
          FILE: ${{ matrix.asset }}
        run: |
          git config user.name 'CI Bot'
          git config user.email 'action@github.com'

          # Ensure we have gh-storage locally
          git fetch origin gh-storage:gh-storage || true

          # Stage the file from the PR HEAD and check it out into gh-storage
          git checkout gh-storage || git switch -c gh-storage
          git checkout ${{ github.event.pull_request.head.sha }} -- "$FILE"

          git add "$FILE"
          git commit -m "Sync static file $FILE to gh-storage" || echo "No changes to commit."

      - name: Push static file(s) to gh-storage
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MAX_RETRIES=5
          for i in $(seq 1 $MAX_RETRIES); do
            git push origin gh-storage --force && break || {
              echo "Push $i failed... retrying"
              sleep 10
            }
          done

  generate_html:
    # Run even if one of the upstream jobs was skipped, but only on merged PRs.
    if: always() && github.event.pull_request.merged == true
    needs: [execute-notebooks, sync-static, prepare_matrix]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bring gh-storage contents into workspace
        shell: bash
        run: |
          git fetch origin gh-storage
          # Pull ALL tracked files from gh-storage (not just notebooks/) so README.md / static HTML are included
          git checkout origin/gh-storage -- .
          # Optional: show what’s going to be built
          git status --porcelain

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install ghp-import
          pip install jupyter-book==0.15.1
          pip install myst-nb
          pip install astroid
          pip install nbval
          # Workaround for jsonschema compat
          pip install jsonschema==4.6.0
          echo "PATH=${PATH}:${HOME}/.local/bin" >> $GITHUB_ENV

      - name: Build HTML
        run: |
          jupyter-book build .

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
