# Example workflow for on-demand notebook testing
# Copy this file to your repository's .github/workflows/ directory

name: Notebook CI - On Demand

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.11'
        type: choice
        options:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
      execution-mode:
        description: 'Execution mode'
        required: true
        default: 'full'
        type: choice
        options:
          - 'validation-only'
          - 'full'
          - 'quick'
      single-notebook:
        description: 'Path to single notebook (optional)'
        required: false
        type: string
      run-security-scan:
        description: 'Run security scan'
        required: false
        default: true
        type: boolean
      build-documentation:
        description: 'Build HTML documentation'
        required: false
        default: true
        type: boolean

jobs:
  on-demand-ci:
    uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_pipeline.yml@main
    with:
      python-version: ${{ inputs.python-version }}
      execution-mode: ${{ inputs.execution-mode }}
      single-filename: ${{ inputs.single-notebook }}
      build-html: ${{ inputs.build-documentation }}
      security-scan: ${{ inputs.run-security-scan }}
    secrets:
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}

  build-docs-on-demand:
    if: inputs.build-documentation == true
    uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_html_builder.yml@main
    with:
      python-version: ${{ inputs.python-version }}
      post-run-script: "scripts/jdaviz_image_replacement.sh"  # Optional
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
