name: Count Tagged Issues

on:
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  count-issues:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.issue-count-postscan.outputs.diff }}
      scan_outcome : ${{ steps.run_html_a11y_scanner.outcome }}
    env:
      GH_TOKEN: ${{ secrets.A11Y_TOKEN }}
      TARGET_LABEL: "axe-scanning-issue"
    steps:
      - name: Count open issues (pre-scan)
        id: issue-count-prescan
        run: |
          # Fetch open issues with the label and get the count using jq length
          COUNT=$(gh issue list --repo "${{ github.repository }}" --label "$TARGET_LABEL" --state open --json number | jq '. | length')
          echo "Found $COUNT open issues with the label '$TARGET_LABEL'."
          # Save the count to output so other steps can use it
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Run HTML accessibility scanner
        id: run_html_a11y_scanner
        run: |
          echo "HTML a11y scanner runs here!"

      - name: Count open issues (post-scan) and compute difference from pre-scan value
        id: issue-count-postscan
        run: |
          # Fetch open issues with the label and get the count using jq length
          COUNT=$(gh issue list --repo "${{ github.repository }}" --label "$TARGET_LABEL" --state open --json number | jq '. | length')
          echo "Found $COUNT open issues with the label '$TARGET_LABEL'."
          # Compute postscan - prescan difference
          DIFF=$(( $COUNT-${{ steps.issue-count-prescan.outputs.count }} ))
          echo "diff=$DIFF" >> $GITHUB_OUTPUT

  summary:
    runs-on: ubuntu-latest
    needs: count-issues
    steps:
      - name: Summary
        run: |
          enable_a11y_html_check="true"
          if [ "$enable_a11y_html_check" = "true" ]; then
            echo "**🔦 HTML Accessibility Check**"
            if [ ${{ needs.count-issues.outputs.scan_outcome }} = "success"]; then
              DIFF=${{ needs.count-issues.outputs.diff}}
              if [ "$DIFF" -eq 0 ]; then
                echo "- **Status**: ✅ SUCCESS - No accessibility problems found."
              else
                if [ "$DIFF" -eq 1 ]; then
                  PLURAL=""
                else
                  PLURAL="s"
                fi
                echo "- **Status**: ⚠️ FAILURE - Accessibility problem$PLURAL found. $DIFF new issue$PLURAL tagged with ['axe-scanning-issue'](https://github.com/spacetelescope/${{ github.event.repository.name }}/issues?q=is%3Aissue%20state%3Aopen%20label%3Aaxe-scanning-issue) have been automatically created."
              fi
            elif [ ${{ count-issues.outputs.scan_outcome }} = "skipped"]; then
              echo "- **Status**: ℹ️  SCAN SKIPPED - There were no new HTML files to scan."
            else
            fi
          fi